### ISSUE TITLE
Unit files which don't following the naming scheme

### ISSUE THREAD

**Issue by Quitch** [nicb1/Broken_Alliance_IL#14]
Large numbers of unit files don't follow the naming scheme of being prefixed with L_. Is this an indication that they're not yet implemented and the files are placeholders?

**Comment by KillerKiwiJuice** [comment]
ATM there's only 3 units without the L_ prefix, and 2 of them are being used. They are really (before I joined this party) old so I didn't bother changing the names.

**Comment by KillerKiwiJuice** [comment]
This is also fixed afaik
