### ISSUE TITLE
Vanilla has access to IL energy

### ISSUE THREAD

**Issue by Quitch** [nicb1/Broken_Alliance_IL#15]
The basic energy plant is accessible to vanilla bot fabbers. Maybe others.

**Comment by KillerKiwiJuice** [comment]
That's because we need to add the -Custom1 buildable_type to ALL vanilla fabbers, then the Custom2 UNITTYPE to all vanilla units, then -Custom2 buildable_type to ALL legion fabbers. Tedious.

**Comment by Quitch** [comment]
Wait, custom2 on the fabbers? Why not custom1?

**Comment by KillerKiwiJuice** [comment]
I'm pretty sure this is fixed so I'm closing it
