### ISSUE TITLE
Orbital Units 

### ISSUE THREAD

**Issue by KillerKiwiJuice** [nicb1/Broken_Alliance_IL#17]
They're a real pain in the ass and I have no idea how to fix them, so I didn't commit them.

**Comment by Stuart1998** [comment]
What's the probblem with them exactly?

**Comment by KillerKiwiJuice** [comment]
The models are fine in 3DS max but in-game they're all screwy. The SXX is HUGE and the orbital fighter is rotated 90 degrees on either the x or y axis can't remember.

**Comment by Stuart1998** [comment]
You're not doing anything derp with the scaling?

Compared with structure of vanilla orbital?

**Comment by KillerKiwiJuice** [comment]
no stuart, no i'm not. The 3ds max files should be absolutely fine, and scaling is in meters.

**Comment by KillerKiwiJuice** [comment]
I solved this issue
